### ISSUE TITLE
live update product prices for related options

### ISSUE THREAD

**Issue by mmojadad** [ocmod-space/ocmod-live-product#2]
Hello
I am a using TDM Conditional Options / Dependent Options, Live price not working for child ( Related Options ).

**Comment by anykeyist** [comment]
> I am a using TDM Conditional Options / Dependent Options, Live price not working for child ( Related Options ).

Hello, 

Obvious, it's impossible to ensure compatibility of all modules in the world out of the box. Create "Get support" request on the module page on OpenCart Marketplace and i will take a look.
